"""Activity entity."""

from dataclasses import dataclass
from typing import Self
from uuid import uuid4

from orgmgr.core.types import ActivityId


MAX_NESTING_LEVEL: int = 3


@dataclass
class Activity:
    """Domain entity representing a activity."""

    activity_id: ActivityId
    parent_id: ActivityId | None
    name: str

    @classmethod
    def create(cls, name: str, parent_id: ActivityId | None) -> Self:
        """Create a new activity entity.

        Args:
            name (str): The name of the activity.
            parent_id (ActivityId | None): The parent of the activity.

        Returns:
            Self: A new activity entity with autogenerated ID and created_at timestamp.
        """
        return cls(
            activity_id=uuid4(),
            name=name,
            parent_id=parent_id,
        )
