"""Building entity."""

from dataclasses import dataclass
from typing import Self
from uuid import uuid4

from orgmgr.core.types import BuildingId
from orgmgr.lib.entities.coordinate import Coordinate


@dataclass
class Building:
    """Domain entity representing a building."""

    building_id: BuildingId
    address: str
    coordinate: Coordinate

    @classmethod
    def create(cls, address: str, coordinate: Coordinate) -> Self:
        """Create a new building entity.

        Args:
            address (str): The name of the building.
            coordinate (Coordinate): The coordinate of the building.

        Returns:
            Self: A new building entity with autogenerated ID.
        """
        return cls(
            building_id=uuid4(),
            address=address,
            coordinate=coordinate,
        )
