"""Organization activity."""

from dataclasses import dataclass
from typing import Self

from orgmgr.core.types import ActivityId, OrganizationId


@dataclass(frozen=True, slots=True)
class OrganizationActivity:
    """Represents the relationship between an organization and an activity."""

    organization_id: OrganizationId
    activity_id: ActivityId

    @classmethod
    def create(cls, organization_id: OrganizationId, activity_id: ActivityId) -> Self:
        """Create a new association between an organization and an activity.

        Args:
            organization_id (OrganizationId): The unique identifier for the organization.
            activity_id (ActivityId): The unique identifier for the activity.

        Returns:
            Self: A new organization activity entity with autogenerated ID.
        """
        return cls(
            organization_id=organization_id,
            activity_id=activity_id,
        )
