"""Organization entity."""

from dataclasses import dataclass
from typing import Self
from uuid import uuid4

from orgmgr.core.types import ActivityId, BuildingId, OrganizationId
from orgmgr.lib.entities.phone_number import PhoneNumber


@dataclass
class Organization:
    """Domain entity representing a organization."""

    organization_id: OrganizationId
    building_id: BuildingId
    activity_ids: list[ActivityId]
    name: str
    phone_numbers: list[PhoneNumber]

    @classmethod
    def create(
        cls,
        building_id: BuildingId,
        activity_ids: list[ActivityId],
        name: str,
        phone_numbers: list[PhoneNumber],
    ) -> Self:
        """Create a new organization entity.

        Args:
            building_id (BuildingId): The building ID of the organization.
            activity_ids (list[ActivityId]): The activity IDs of the organization.
            name (str): The name of the organization.
            phone_numbers (list[PhoneNumber]): The phone numbers of the organization.

        Returns:
            Self: A new organization entity with autogenerated ID.
        """
        return cls(
            organization_id=uuid4(),
            building_id=building_id,
            activity_ids=activity_ids,
            name=name,
            phone_numbers=phone_numbers,
        )
