services:
  db:
    image: postgres:18-alpine

    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Required variable POSTGRES_USER not set}
      POSTGRES_DB: ${POSTGRES_DB:?Required variable POSTGRES_DB not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Required variable POSTGRES_PASSWORD not set}

    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:8-alpine

    ports:
      - 127.0.0.1:6379:6379
