"""Add Activity.

Revision ID: 34c11c989d8d
Revises: 000000000000
Create Date: 2025-10-20 12:41:22.768761+00:00
"""

import sqlalchemy as sa
from alembic import op


revision = "34c11c989d8d"
down_revision = "000000000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activities")
    # ### end Alembic commands ###
